openapi: 3.0.0
info:
  description: 
    This is a pds-phenotype-mapping-plugin.  You can find
    out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: "1.0.0"
  title: pds-aggregator-plugin
  license:
    name: MIT
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /guidance:
    get:
      summary: Collect a list of variables with their values from profile plugin and dosing guidance. Wrap it up and return
      operationId: api.getGuidance
      parameters:
        - in: query
          name: patient_id
          example: 38
          schema:
            type: string
          required: true
        - in: query
          name: model
          schema:
            type: string
          required: true
        - in: query
          name: model_plugin_id
          example: "pdsmpi-ref"
          schema:
            type: string
          required: true
        - in: query
          name: timestamp
          example: "2019-12-03T13:41:09.942+00:00"
          schema:
            type: string
          required: true
      responses: # has to match output of dispatcher.py
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aggregate'
        '405':
          description: Invalid input
  /profile:
    get:
      summary: Add patient record directory, patient_id, system and diagnosis code
      operationId: api.getProfile
      parameters:
        - in: query
          name: patient_id
          example: 38
          schema:
            type: string
          required: true
        - in: query
          name: model_plugin_id
          example: "pdsmpi-ref"
          schema:
            type: string
          required: true
        - in: query
          name: timestamp
          example: "2019-12-03T13:41:09.942+00:00"
          schema:
            type: string
          required: true
      responses: # has to match output of dispatcher.py
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aggregate'
        '405':
          description: Invalid input
components:
  schemas:
    Aggregate:
      type: object
      properties:
        features:
          type: array
          items:
            type: object
            properties:
              clinical_feature_variable:
                type: string
                example: "LOINC:29463-7"
              title:
                type: string
              value: {}
              calculation:
                type: string
                example: 1
              certitude:
                type: integer
              description:
                type: string
            required:
              - clinical_feature_variable
              - value
              - calculation
              - certitude
              - description
              - title
        guidance: {}
