openapi: 3.0.0
info:
  description: 
    This is a pds-phenotype-mapping-plugin.  You can find
    out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: "1.0.0"
  title: pds-aggregator-plugin
  license:
    name: MIT
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /pg:
    get:
      summary: Add patient record directory, patient_id, system and diagnosis code
      operationId: api.getAggregator
      parameters:
        - in: query
          name: patient_id
          schema:
            type: string
          required: true
        - in: query
          name: model
          schema:
            type: string
          required: true
        - in: query
          name: model_plugin_id
          schema:
            type: string
          required: true
        - in: query
          name: timestamp
          schema:
            type: string
          required: true
      responses: # has to match output of dispatcher.py
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aggregate'
        '405':
          description: Invalid input
components:
  schemas:
    Aggregate:
      type: object
      properties:
        features:
          type: array
          items:
            type: object
            properties:
              clinical_feature_variable:
                type: string
              title:
                type: string
              value: {}
              calculation:
                type: string
              certitude:
                type: integer
              description:
                type: string
            required:
              - clinical_feature_variable
              - value
              - calculation
              - certitude
              - description
              - title
        guidance: {}
