openapi: 3.0.0
# Added by API Auto Mocking Plugin
info:
  description: Simple PDS plugin
  version: "1.0.0"
  title: Simple PDS API
  contact:
    email: txscience@lists.renci.org
paths:
  /guidance:
    post:
      summary: given a patient ID and a plugin id, return the guidance
      operationId: api.get_guidance
      responses:
        '200':
          description: guidance matching query
          content: 
            application/json:
              schema:
                  $ref: '#/components/schemas/Guidance'
        '400':
          description: bad input parameter
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GuidanceInputs'
  /profile:
    get:
      summary: Add patient record directory, patient_id, system and diagnosis code
      operationId: api.get_profile
        parameters:
        - in: query
          name: ptid
          example: 38
          schema:
            type: string
          required: true
        - in: query
          name: piid
          example: "pdspi-guidance-example"
          schema:
            type: string
          required: true
        - in: query
          name: timestamp
          example: "2019-12-03T13:41:09.942+00:00"
            schema:
              type: string
          required: true
      responses: # has to match output of dispatcher.py
        '200':
          description: Successful operation
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/PatientVariable'
        '405':
          description: Invalid input
  /config:
    get:
      summary: gets list of plugins with their selectors and required variables
      operationId: api.get_config
      parameters:
        - name: piid
          example: "pdspi-guidance-example"
          in: query
          required: false
          schema:
            type: string
          description: if present, return PluginConfig tailored to include only information about the indicated plugin. if not present, return all guidance piids and their info
      responses:
        '200':
          description: config matching query
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PluginConfig'
        '400':
          description: bad input parameter
components:
  schemas:
    GuidanceInputs:
      type: object
      required:
        - piid
        - ptid
        - timestamp
      properties:
        piid:
          type: string
          example: "pdspi-guidance-example"
          description: uniquely identifies the enabled and installed plugin to use for retrieving guidance
        ptid:
          type: string
          example: "38"
          description: the ID of the patient for which guidance is required
        timestamp:
          type: string
          format: date-time
          example: "2019-12-03T13:41:09.942+00:00"
        pluginParameterValues:
          type: array
          items:
            $ref: '#/components/schemas/PluginParameter'
        userSuppliedPatientVariables:
          type: array
          items:
            $ref: '#/components/schemas/PatientVariable'
    Guidance:
      type: object
      properties:
        title:
          type: string
        id:
          type: string
        justification:
          type: array
          items:
            $ref: '#/components/schemas/PatientVariable'
          description: "a list of patient variables that were used and how they were computed and why they were needed "
        cards:
          type: array
          items:
            $ref: '#/components/schemas/Card'
    Card:
      type: object
      required:
        - id
        - summary
        - indicator
        - source
      properties:
        id: 
          type: string
        title:
          type: string
        summary:
          type: string
          description: "cds-hooks: <140-character summary sentence for display to the user inside of this card"
          example: "some <140 char Summary Message"
        detail:
          type: string
          description: "cds-hooks: - optional detailed information to display (GitHub Flavored Markdown)"
          example: "some sort of optional GitHub Markdown details"
        indicator:
          type: string
          description: " urgency/importance of what this card conveys (info/warning/critical)"
          example: "info"
        source:
          $ref: "#/components/schemas/Source"
        suggestions:
          type: array
          items:
            $ref: '#/components/schemas/Suggestion'
        selectionBehavior:
          type: string
          description: " intended behavior of the suggestions. If suggestions present, value must be at-most-one"
        links: 
          type: array
          items:
            $ref: '#/components/schemas/Link'
    Source:
      type: object
      required:
        - label
      properties:
        label:
          type: string
          description: "short, human-readable label to display source of the card’s information"
          example: Human-readable source label
        url:
          type: string
          description: "optional absolute URL to load to learn more about the organization or data set"
          example: "https://example.com"
        icon:
          type: string
          description: " absolute url for an icon for the source of this card (100x100 pixel PNG without any transparent regions)"
          example: "https://example.com/img/icon-100px.png"
    Suggestion:
      type: object
      required:
        - label
      properties:
        uuid:
          type: string
          description: "unique identifier for auditing and logging suggestions"
          example: e1187895-ad57-4ff7-a1f1-ccf954b2fe46
        label:
          type: string
          description: "human-readable label to display for this suggestion"
          example: "Human-readable suggestion label"
        actions:
          type: array
          items:
            $ref: '#/components/schemas/Action'
    Action:
      type: object
      required:
        - type
        - description
      properties:
        title:
          type: string
        id:
          type: string
        type:
          type: string
          description: "type of action being performed (create/update/delete)"
          example: "create"
        description:
          type: string
          description: "human-readable description of the suggested action"
          example: "Create a prescription for Acetaminophen 250 MG"
        resource:
          type: string
          description: "FHIR resource to create/update or id of resource to delete"
          example: "MedicationRequest"
    Link:
      type: object
      required:
        - label
        - url
        - type
      properties:
        label:
          type: string
          description: "human-readable label to display"
          example: "SMART Example App"
        url:
          type: string
          description: "URL to GET when link is clicked"
        type:
          type: string
          description: "type of the given URL (absolute/smart) "
        appContext:
          type: string
          description: "additional context to share with a linked SMART app"
    PluginConfig:
      type: object
      properties:
        title:
          type: string
          description: "Meaningful name for this plugin"
          example: "Aminogycoside dosing guidance"
        piid:
          type: string
          description: "A string, unique to this deployment, used to identify this plugin in realtime"
          example: "pdspi-aminogycoside-nomogram"
        pluginSelectors:
          type: array
          items:
            $ref: '#/components/schemas/PluginSelector'
        pluginParameterDefaults:
          type: array
          items:
            $ref: '#/components/schemas/PluginParameter'
        requiredPatientVariables:
          type: array
          items:
            $ref: '#/components/schemas/PatientVariableType'
    PluginSelector:
      description: The combination of selector values map to a unique plugin. That is, no two plugins can install with the identical vectors of selector values.  
      type: object
      properties:
        title:
          type: string
          example: "Gentamicin"
        code:
          type: string
          example: "1596450"
        selectorType:
          $ref: '#/components/schemas/PluginSelectorType'
    PluginSelectorType:
      description: Plugins providing Drug selector types will always use RxCUI when naming the drug. Diagnosis types will use ICD10, and genetics will use SNP for variants and NCBI for gene and transcript names.  
      type: object
      properties:
        title:
          type: string
          example: "Drug"
        system:
          type: string
          example: "RxCUI"
    PluginParameter:
      type: object
      properties:
        value:
          type: string
          description: the actual value of the model parameter
          example: "Hartford"
        units:
          type: string
          description: "The unit is standard throughout the pds system. It's up to the guidance plugin to make unit conversions as needed by the guidance model, just as it is up to the dashboard to make unit conversions as needed by the end user."
          example: "none"
        parameterType:
          $ref: '#/components/schemas/PluginParameterType'
    PluginParameterType:
      type: object
      properties:
        title:
          type: string
          example: "Extended interval nomogram"
        code:  
          type: string
          example: "PDS:01"
        system: 
          type: string
          example: "PDS.plugin.parameters"
        legalValues:
          type: string
          example: 'enum: ["Hartford", "Urban-Craig", "Conventional A", "Conventional B"]'
        description:
          type: string
          example: "This calculator uses one of four extended-interval nomograms. Please choose one nomogram."
    PatientVariable:
      type: object
      properties:
        value:
          type: string
          description: the actual value of the patient variable. If 'pds-retrieve-datum' then retrieve from patient data warehouse, otherwise use the value as-is
          example: "0.5"
        units:
          type: string
          description: "The unit is standard throughout the pds system. It's up to the guidance plugin to make unit conversions as needed by the guidance model, just as it is up to the dashboard to make unit conversions as needed by the end user."
          example: "years"
        how:
          type: string
          description: "If the variable is 'pds-retrieve-datum', then 'how' will read 'The value was specified by the end user.'"
          example: "The value was specified by the end user."
        variableType:
          $ref: '#/components/schemas/PatientVariableType'
    PatientVariableType:
      type: object
      properties:
        title:
          type: string
          example: "Age"
        clinicalFeatureVariable:
          type: string
          example: "LOINC:30525-0"
        description: 
          type: string
          example: "Age is a floating point number; e.g., a 6 month old child is 0.5 years."
        why:
          type: string
          example: "Age is used to calculate the creatinine clearance. Dosing is lower for geriatric patient and contraindicated for pediatric patients"
